### ISSUE TITLE
Allow arbitrary content (ie. <b>, <br /> tags)

### ISSUE THREAD

**Issue by bebraw** [bebraw/jquery.ellipsis#4]
Now the solution relies on `text()`. The problem with this is that it loses formatting. Here's a better solution:
- Extract html - ie. html()
- Convert html to intermediate structure - `"foo \<b\>bar\</b\>\<br /\> another line"` to

``` javascript
[
    {text: 'foo ', node: null, children: null},
    {text: 'bar', node: 'b', children: null},
    {text: null, node: 'br', children: null},
    {text: ' another line', node: null, children: null}
]
```
- Perform analysis over structure (it can be nested!). This would operate over text fields. The key thing here is that you want to understand which node it should modify and which ones to discard. As a result of analysis you would end up with a subset of above structure like this.
- Construct html

**Comment by banifou** [comment]
Great! Can' wait to use it.
